-- UmaToolbox admin database schema (Supabase / Postgres)
--
-- Run this once in your Supabase project's SQL Editor (Project > SQL Editor > New query)
-- after creating the project. Then run seed.sql (generated by
-- scripts/generate_seed_sql.py) to load your existing data.
--
-- Design: flat columns, not nested JSON, so every field is its own editable
-- cell in Supabase's built-in Table Editor - no raw JSON to hand-edit there.
-- The site reshapes rows back into the nested shape the JS already expects
-- when it fetches them (see js/supabase.js).

create table if not exists umas (
  id bigint generated always as identity primary key,
  name text not null,
  costume text,
  version text,
  in_game boolean not null default false,
  unique_skill_name text,
  unique_condition text,
  pre_condition_note text,
  dist_aptitude text,
  style text,
  target_speed_bonus numeric,
  acceleration_bonus numeric,
  heal_bonus numeric,
  unique_effect_note text,
  duration numeric,
  -- Aptitude grades: A/B/C/D/E/F/G (A best), one column per dimension so
  -- each is independently editable/sortable in the table editor.
  apt_turf text,
  apt_dirt text,
  apt_sprint text,
  apt_mile text,
  apt_medium text,
  apt_long text,
  apt_front text,
  apt_pace text,
  apt_late text,
  apt_end text,
  stat_spd numeric,
  stat_sta numeric,
  stat_pwr numeric,
  stat_gut numeric,
  stat_wit numeric,
  note text,
  release_date date
);

create table if not exists supports (
  id bigint generated always as identity primary key,
  character text,
  name text not null,
  in_game boolean not null default false,
  type text,
  grade text,
  lb_pips numeric,
  friendship_bonus numeric,
  motivation_effect numeric,
  training_bonus numeric,
  effect_m_plus_t_bonus numeric,
  total_bonus numeric,
  init_stat numeric,
  init_gauge numeric,
  race_bonus numeric,
  fan_bonus numeric,
  hint_level numeric,
  hint_frequency numeric,
  skill_pt_priority numeric,
  skill_pt_bonus numeric,
  notes text,
  friendship_ratio numeric,
  release_date date
);

create table if not exists races (
  id bigint generated always as identity primary key,
  name text not null,
  -- Lets you add a race that exists in game data before it actually goes
  -- live (e.g. Prix Foy) - it stays out of the planner grid until flipped.
  in_game boolean not null default true,
  grade text,
  dist_type text,
  meters integer,
  date_index integer,
  slot text, -- e.g. "Junior Late Jun" - one of the 72 calendar slots
  phase text, -- Junior / Classic / Senior
  surface text,
  racecourse text,
  course text,
  direction text,
  -- Text, not a number: some races (JBC day, for example) run several races
  -- back to back with different fields sizes, e.g. "16/14/14/16".
  participants text,
  time_of_day text,
  base_fans integer,
  url_slug text, -- also used to look up this race's image, see below
  fans_required integer,
  fans_gained integer
);

-- Row Level Security: the site's public pages read with the anon key, which
-- must only ever be able to SELECT. Editing happens exclusively through the
-- Supabase dashboard (Table Editor), where you're authenticated as the
-- project owner and RLS doesn't apply to you.
alter table umas enable row level security;
alter table supports enable row level security;
alter table races enable row level security;

drop policy if exists "Public read access" on umas;
create policy "Public read access" on umas for select using (true);

drop policy if exists "Public read access" on supports;
create policy "Public read access" on supports for select using (true);

drop policy if exists "Public read access" on races;
create policy "Public read access" on races for select using (true);

-- No insert/update/delete policies are created for the anon/authenticated
-- roles, which means the public API can only ever read - never write.

-- Public storage bucket for race nameplate images. Files are matched to
-- races by name: upload/replace "{url_slug}.png" (see url_slug on each race
-- row) and it's picked up automatically - no other config needed. "Public"
-- means anyone can view a file at its URL; only you (via the dashboard,
-- authenticated as the project owner) can upload or replace one.
insert into storage.buckets (id, name, public)
values ('race-images', 'race-images', true)
on conflict (id) do nothing;

-- Same idea for trainee portraits, matched by the trainee's name slugified
-- the same way the site does it (lowercase, non-alphanumeric runs -> single
-- hyphen, trimmed) - see slugify() in js/common.js. There's no url_slug
-- column on umas to read it from directly; either work it out by hand
-- (e.g. "Oguri Cap" -> "oguri-cap") or check the Network tab for the exact
-- attempted filename on a trainee whose portrait is missing.
insert into storage.buckets (id, name, public)
values ('trainee-images', 'trainee-images', true)
on conflict (id) do nothing;
