-- UmaToolbox admin database schema (Supabase / Postgres)
--
-- Run this once in your Supabase project's SQL Editor (Project > SQL Editor > New query)
-- after creating the project. Then run seed.sql (generated by
-- scripts/generate_seed_sql.py) to load your existing data.
--
-- Design: flat columns, not nested JSON, so every field is its own editable
-- cell in Supabase's built-in Table Editor - no raw JSON to hand-edit there.
-- The site reshapes rows back into the nested shape the JS already expects
-- when it fetches them (see js/supabase.js).

create table if not exists umas (
  id bigint generated always as identity primary key,
  name text not null,
  costume text,
  version text,
  in_game boolean not null default false,
  unique_skill_name text,
  unique_condition text,
  pre_condition_note text,
  dist_aptitude text,
  style text,
  target_speed_bonus numeric,
  acceleration_bonus numeric,
  heal_bonus numeric,
  unique_effect_note text,
  duration numeric,
  -- Aptitude grades: A/B/C/D/E/F/G (A best), one column per dimension so
  -- each is independently editable/sortable in the table editor.
  apt_turf text,
  apt_dirt text,
  apt_sprint text,
  apt_mile text,
  apt_medium text,
  apt_long text,
  apt_front text,
  apt_pace text,
  apt_late text,
  apt_end text,
  stat_spd numeric,
  stat_sta numeric,
  stat_pwr numeric,
  stat_gut numeric,
  stat_wit numeric,
  note text,
  release_date date
);

create table if not exists supports (
  id bigint generated always as identity primary key,
  character text,
  name text not null,
  in_game boolean not null default false,
  type text,
  grade text,
  lb_pips numeric,
  friendship_bonus numeric,
  motivation_effect numeric,
  training_bonus numeric,
  effect_m_plus_t_bonus numeric,
  total_bonus numeric,
  init_stat numeric,
  init_gauge numeric,
  race_bonus numeric,
  fan_bonus numeric,
  hint_level numeric,
  hint_frequency numeric,
  skill_pt_priority numeric,
  skill_pt_bonus numeric,
  notes text,
  friendship_ratio numeric,
  release_date date
);

-- Row Level Security: the site's public pages read with the anon key, which
-- must only ever be able to SELECT. Editing happens exclusively through the
-- Supabase dashboard (Table Editor), where you're authenticated as the
-- project owner and RLS doesn't apply to you.
alter table umas enable row level security;
alter table supports enable row level security;

drop policy if exists "Public read access" on umas;
create policy "Public read access" on umas for select using (true);

drop policy if exists "Public read access" on supports;
create policy "Public read access" on supports for select using (true);

-- No insert/update/delete policies are created for the anon/authenticated
-- roles, which means the public API can only ever read - never write.
