"""
Generates db/seed.sql from the current data/umas.json and data/supports.json,
for a one-time load into a fresh Supabase project (after running db/schema.sql).

    python scripts/generate_seed_sql.py

This is a one-time migration aid, not something you re-run routinely - once
the data lives in Supabase, you edit it there directly.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
OUT_FILE = ROOT / "db" / "seed.sql"


def sql_str(v):
    if v is None:
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def sql_bool(v):
    return "true" if v else "false"


def sql_num(v):
    return "null" if v is None else str(v)


UMA_COLUMNS = [
    "name", "costume", "version", "in_game", "unique_skill_name", "unique_condition",
    "pre_condition_note", "dist_aptitude", "style", "target_speed_bonus",
    "acceleration_bonus", "heal_bonus", "unique_effect_note", "duration",
    "apt_turf", "apt_dirt", "apt_sprint", "apt_mile", "apt_medium", "apt_long",
    "apt_front", "apt_pace", "apt_late", "apt_end",
    "stat_spd", "stat_sta", "stat_pwr", "stat_gut", "stat_wit",
    "note", "release_date",
]


def uma_row(u):
    apt = u.get("aptitude") or {}
    stat = u.get("statBonus") or {}
    return [
        sql_str(u.get("name")), sql_str(u.get("costume")), sql_str(u.get("version")),
        sql_bool(u.get("inGame")), sql_str(u.get("uniqueSkillName")), sql_str(u.get("uniqueCondition")),
        sql_str(u.get("preConditionNote")), sql_str(u.get("distAptitude")), sql_str(u.get("style")),
        sql_num(u.get("targetSpeedBonus")), sql_num(u.get("accelerationBonus")), sql_num(u.get("healBonus")),
        sql_str(u.get("uniqueEffectNote")), sql_num(u.get("duration")),
        sql_str(apt.get("turf")), sql_str(apt.get("dirt")), sql_str(apt.get("sprint")),
        sql_str(apt.get("mile")), sql_str(apt.get("medium")), sql_str(apt.get("long")),
        sql_str(apt.get("front")), sql_str(apt.get("pace")), sql_str(apt.get("late")), sql_str(apt.get("end")),
        sql_num(stat.get("spd")), sql_num(stat.get("sta")), sql_num(stat.get("pwr")),
        sql_num(stat.get("gut")), sql_num(stat.get("wit")),
        sql_str(u.get("note")), sql_str(u.get("release")),
    ]


SUPPORT_COLUMNS = [
    "character", "name", "in_game", "type", "grade", "lb_pips",
    "friendship_bonus", "motivation_effect", "training_bonus", "effect_m_plus_t_bonus", "total_bonus",
    "init_stat", "init_gauge", "race_bonus", "fan_bonus",
    "hint_level", "hint_frequency", "skill_pt_priority", "skill_pt_bonus",
    "notes", "friendship_ratio", "release_date",
]


def support_row(s):
    return [
        sql_str(s.get("character")), sql_str(s.get("name")), sql_bool(s.get("inGame")),
        sql_str(s.get("type")), sql_str(s.get("grade")), sql_num(s.get("lbPips")),
        sql_num(s.get("friendshipBonus")), sql_num(s.get("motivationEffect")), sql_num(s.get("trainingBonus")),
        sql_num(s.get("effectMPlusTBonus")), sql_num(s.get("totalBonus")),
        sql_num(s.get("initStat")), sql_num(s.get("initGauge")), sql_num(s.get("raceBonus")), sql_num(s.get("fanBonus")),
        sql_num(s.get("hintLevel")), sql_num(s.get("hintFrequency")),
        sql_num(s.get("skillPtPriority")), sql_num(s.get("skillPtBonus")),
        sql_str(s.get("notes")), sql_num(s.get("friendshipRatio")), sql_str(s.get("release")),
    ]


def build_insert(table, columns, rows):
    lines = [f"insert into {table} ({', '.join(columns)}) values"]
    value_lines = [f"  ({', '.join(row)})" for row in rows]
    lines.append(",\n".join(value_lines) + ";")
    return "\n".join(lines)


def main():
    umas = json.loads((DATA_DIR / "umas.json").read_text(encoding="utf-8"))
    supports = json.loads((DATA_DIR / "supports.json").read_text(encoding="utf-8"))

    parts = [
        "-- Generated by scripts/generate_seed_sql.py - run once in Supabase's SQL Editor",
        "-- after schema.sql. Safe to re-run against an empty table; will duplicate rows",
        "-- if the tables already have data (truncate first if re-seeding).",
        "",
        build_insert("umas", UMA_COLUMNS, [uma_row(u) for u in umas]),
        "",
        build_insert("supports", SUPPORT_COLUMNS, [support_row(s) for s in supports]),
        "",
    ]

    OUT_FILE.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT_FILE} ({len(umas)} umas, {len(supports)} supports)")


if __name__ == "__main__":
    main()
